### ISSUE TITLE
关于NSVB

### ISSUE THREAD

**Issue by suzhenghang** [MoonInTheRiver/NeuralSVB#4]
听了[demo](https://neuralsvb.github.io/)后有些疑问，
1 如果实际使用来美化唱歌，那么Inference的时候是需要原唱的pitch curve对吧？
2 虽然测试样例不在训练样本中，但是GT Professional和GT Amateur是同一个人录制的。Inference中GT Professional不可能是自己，这样泛化性有测试过吗？

**Comment by MoonInTheRiver** [comment]
数据集里只有“同一句歌词，同一个歌手，不同唱法演唱”的GT样本。
没有“同一句歌词，不同歌手演唱”的GT样本，故无法量化的进行对照实验。
感兴趣的话可以利用我们的代码进行二次创作。
