### ISSUE TITLE
Problem with proper data loading

### ISSUE THREAD

**Issue by pstryczke** [MoonInTheRiver/NeuralSVB#5]
Hi, I'd like to run your model by myself, however I cannot find proper way to load the dataset with .mp3 files you provided. Is there a chance to share the dataloader you've used or give some hints how to process the .mp3 files to valid dataset which could be used in your usage examples? I'll be very grateful!

**Comment by galfaroth** [comment]
+1 I faced exact same rabbit hole. Anyone successfully ran the project or it's only paper with some unstructured chunks that can't be ran?

**Comment by MrZixi** [comment]
Uh, the .mp3 files need to be processed and binarized. We are still clearing the codes up. But maybe refer to [files](https://github.com/MoonInTheRiver/DiffSinger/tree/master/data_gen) as well as the data preparation process in that repo.

**Comment by pstryczke** [comment]
@MrZixi 
There is a csv file in [base_binarizer.py](https://github.com/MoonInTheRiver/DiffSinger/blob/master/data_gen/tts/base_binarizer.py#L134) from which some parameters are gained and used in further files processing, however I cannot find any reference where and how this csv file is created. Any advices? Thanks :)

**Comment by galfaroth** [comment]
Good question, I was reading through the code and was lost there too. @MrZixi mind you know what these .csv files are?

**Comment by MrZixi** [comment]
The csv file is generated by preprocessing codes. See [here](https://github.com/MoonInTheRiver/DiffSinger/tree/master/data/processed/ljspeech), an example of preprocessed Ljspeech dataset. They are basically doing things like recording wav file paths, normalizing texts, extracting phoneme and aligning phoneme sequences with wav using MFA tools.

**Comment by pstryczke** [comment]
As I can see, the given csv example has different column names than the keys used in NeuralSVB dataloaders, which prevents us from properly preprocessing the data. Are you going to upload some working examples for NeuralSVB repository? Thank you

**Comment by galfaroth** [comment]
the job demands columns like 'f0', 'uv', 'me12ph', 'me', 'prof_f0' and the code @MrZixi you provided generates 'spk', 'txt', 'txt_raw', 'ph', 'wav_fn'. Can you please explain how to properly load the demo dataset and start training the model?

**Comment by galfaroth** [comment]
@MrZixi ?

**Comment by MrZixi** [comment]
> 
The code I referred to is an example from one of our other repos. The point is that the columns which NeuralSVB needs are processed by those codes. For example, the 'prof_f0' and 'f0' represent the amateur f0 and professional f0 information from the paired pieces. The 'mel2ph' represents the alignment between phonemes and the mel-spectrogram provided by the MFA tool. We are still clearing the codes up and it may take some time as we are now been occupied by some other things.

**Comment by pstryczke** [comment]
@MrZixi 
But it still doesn't help us, as we have no idea how such 'f0', 'prof_f0' or 'mel2ph' binaries should be represented or preprocessed. You can try to run training from files in this repo to find out what is missing (of course except audio samples, which you provide separately)

**Comment by galfaroth** [comment]
I think you should probably close this repo as its impossible to run anything and there is none who can help.

**Comment by MrZixi** [comment]
> I think you should probably close this repo as its impossible to run anything and there is none who can help.

Try to learn some manners, will you? Be patient and ask about our time schedule of releasing codes and data to arrange yours or just un-star. (Maybe nonsenses as it looks like you never star this repo)
